#ifndef __ENGINE_HPP__
#define __ENGINE_HPP__

extern "C" {
#include <stdint.h>
typedef unsigned int OpCode;
typedef unsigned int Cond;
typedef int8_t I8;
typedef int16_t I16;
typedef int32_t I32;
typedef int64_t I64;
typedef uint64_t Ref;
typedef uint16_t Flag;

	//***********************************************************************
	//** Warning: this file was generated automatically, don't edit it by hands **
	//***********************************************************************
	//alloca
	void alloca_I8(Ref res, I8 allocator);
	void alloca_I16(Ref res, I16 allocator);
	void alloca_I32(Ref res, I32 allocator);
	void alloca_I64(Ref res, I64 allocator);
	//binop
	void binop_I8(Ref res, OpCode code, Flag flag, Ref arg1, I8 op1, Ref arg2, I8 op2);
	void binop_I16(Ref res, OpCode code, Flag flag, Ref arg1, I16 op1, Ref arg2, I16 op2);
	void binop_I32(Ref res, OpCode code, Flag flag, Ref arg1, I32 op1, Ref arg2, I32 op2);
	void binop_I64(Ref res, OpCode code, Flag flag, Ref arg1, I64 op1, Ref arg2, I64 op2);
	//icmp
	void icmp_I8(Ref res, I8 op1, I8 op2);
	void icmp_I16(Ref res, I16 op1, I16 op2);
	void icmp_I32(Ref res, I32 op1, I32 op2);
	void icmp_I64(Ref res, I64 op1, I64 op2);
	//ite
	bool ite(Ref ret, bool cond);

}
#endif