#!/usr/bin/env python
import fileinput
import sys
#see: https://www.tutorialspoint.com/python/python_xml_processing.htm
import xml.sax
intTy = "$INT"
poly = []
simple = []
unsorted = []
header_prefix = []
header_postfix = []
source_prefix = []
source_postfix = []

#parsing args
argnum = len(sys.argv)
if argnum  == 1:
    pass
elif argnum == 2:
    arg1 = sys.argv[1]
    pass
else:
    print "wrong number of arguments: " + str(argnum)
    sys.exit()
# see: https://interactivepython.org/runestone/static/pythonds/BasicDS/ImplementingaStackinPython.html
class Stack:
     def __init__(self):
         self.items = []
     def isEmpty(self):
         return self.items == []
     def push(self, item):
         self.items.append(item)
     def pop(self):
         return self.items.pop()
     def top(self):
         return self.items[len(self.items)-1]
     def size(self):
         return len(self.items)
    
tagStack = Stack()

# parser

class TemplateHandler (xml.sax.ContentHandler):
    def __init__(self):
        key = ""

    def startElement(self, tag, atts):
        tagStack.push(tag)
        if tag == "func":
            self.name = atts["name"].strip()
        elif tag == "collection":
            self.key = atts["type"].strip()
            
    def endElement(self, tag):
        if tag == "func":
            global poly
            global simple
            global unsorted
            func = (self.ret, self.name, self.header)
            if self.key == "poly":
                poly.append(func)
            elif self.key == "simple":
                simple.append(func)
            else:
                unsorted.append(func)
        tagStack.pop()
            
    def characters(self, str):
        if tagStack.top() == "header_prefix":
            header_prefix.append(str.strip())
        elif tagStack.top() == "header_postfix":
            header_postfix.append(str.strip())
        elif tagStack.top() == "source_prefix":
            source_prefix.append(str.strip())
        elif tagStack.top() == "soruce_postfix":
            source_postfix.append(str.strip())
        elif tagStack.top() == "ret":
            self.ret = str.strip()
        elif tagStack.top() == "header":
            self.header = str.strip()
    
parser = xml.sax.make_parser()
parser.setFeature(xml.sax.handler.feature_namespaces,0)
handler = TemplateHandler()
parser.setContentHandler(handler)

parser.parse(sys.stdin)

# generator

header = open('c-driver.hpp', 'w')
source = open('c-driver.cpp', 'w')

print "// Attention: this file is automatically generated, do not change it manually!"

def printlist(f, l):
    for s in l:
        f.write(s.strip() + "\n")

def printSemiColon(dest):
    dest.write(";\n")
    
def printHead(dest, ret, name, args):
    dest.write("\t" + ret + " " + name + "(" + args + ")")

def printPolyDeclaration(dest, ret, name, args):
    pname = name + "_$INT"
    for i in ["i8", "i16", "i32", "i64"]:
        printHead(dest, ret, pname.replace("$INT", i), args.replace("$INT", i))
        printSemiColon(dest)

def printSimpleDeclaration(dest, ret, name, args):
    printHead(dest, ret, name, args)
    printSemiColon(dest)

def printSimpleDefinition(dest, ret, name, args):
    printHead(dest, ret, name, args)
    dest.write("{}")

def printCollection(dest, title, collection, printer):
    dest.write( "\t// " + title + "\n")
    for func in collection:
        ret = func[0]
        name = func[1]
        args = func[2]
        dest.write("\t//" + name + "\n")
        printer(dest, ret, name, args)

# header
printlist(header, header_prefix)
printCollection(header, "POLY", poly, printPolyDeclaration)
printCollection(header, "SIMPLE", simple, printSimpleDeclaration)
printlist(header, header_postfix)

#source
printlist(source, source_prefix)
printCollection(source, "SIMPLE", simple, printSimpleDefinition)
printlist(source, source_postfix)
