// PASSES
#define RESTRICTION_PASS
#define CONCRETIZATION_PASS

// FIRST OPTIONS
//#define RANDOM_FIRST

// BIGRAM OPTIONS
#define PURE_NEXT
//#define ROULETTE_NEXT
//#define RANDOM_NEXT

// PRINTING
#define CHAR_PRINTING
#define STRING_PRINTING
